GET http://127.0.0.1:3000/

###
POST http://127.0.0.1:3000/api/v1/users/seed

###
POST http://127.0.0.1:3000/api/v1/food/seed


###
POST  http://127.0.0.1:3000/api/v1/stats/seed


###
@jwt={{login.response.body.data.token}}
@port=3000

###
# @name login
POST http://localhost:3000/api/v1/users/login
Content-Type: application/json

{
    "email": "menesesr1@newpaltz.edu",
    "password": "1234abc"
}

// The @name is required so the variable @jwt knows where to get the token from.

###
GET http://localhost:{{port}}/api/v1/users
Authorization: Bearer {{jwt}}

###
POST http://127.0.0.1:3000/api/v1/restaurants/seed
Authorization: Bearer {{jwt}}

// The authorization header is required to authenticate the request.
// this is now required for all requests